# will only start haproxy once as it checks for an haproxy log file
- name: run haproxy
  shell:
    cmd: "( nohup haproxy -f haproxy.cfg > haproxy.log 2>&1 & )"
    chdir: /home/adminuser
    creates: haproxy.log
