# ignore errors because get an error if running this second time after updating scripts/setEnv.sh
- name: Install git
  yum:
    name: git
    state: latest

- name: checkout Digital Banking git repo
  ignore_errors: yes
  git:
    repo: 'https://github.com/jphaugla/Digital-Banking-CockroachDB'
    dest: /home/adminuser/Digital-Banking-CockroachDB
