# add cdc-sink configuration to app node
- name: enable rangefeed
  command: "{{ lookup('template','enable-rangefeed.j2') }}"
- name: create _cdc_sink database
  command: "{{ lookup('template','create-cdc-sink-db.j2') }}"
- name: create dead letter queue
  command: "{{ lookup('template','dead-letter.j2') }}"
- name: start cdc-sink
  shell: 
    cmd: "( nohup ./start.sh > /mnt/datat1/cdc-sink/cdc-sink.log 2>&1 & )"
    chdir: /opt/cdc-sink-linux-amd64-master/
