- name: make log replicator directory
  become: yes
  file: 
    path: "{{ crdb_file_location }}/logs/replicator"
    state: directory
    mode: '0777'
    owner: adminuser
    group: adminuser

- name: make app log directory
  become: yes
  file: 
    path: "{{ crdb_file_location }}/logs/bank-app"
    state: directory
    mode: '0777'
    owner: adminuser
    group: adminuser
