# create der certs
- name: create ca.crt.der
  shell: 
    cmd: "openssl x509 -outform der -in ca.crt -out ca.crt.der"
    chdir: /home/adminuser/certs

- name: create client.jhaugland.crt.der
  shell: 
    cmd: "openssl x509 -outform der -in client.jhaugland.crt -out client.jhaugland.crt.der"
    chdir: /home/adminuser/certs

- name: create client.jhaugland.key.der
  shell: 
    cmd: "openssl pkcs8 -topk8 -inform PEM -outform DER -in client.jhaugland.key -out client.jhaugland.key.der -nocrypt"
    chdir: /home/adminuser/certs
