# save tls keys from app node to local machine
- name: save ca.crt  locally
  fetch:
    dest: "temp/{{ region }}/ca.crt"
    src: /home/adminuser/certs/ca.crt
    flat: yes

- name: save client.jhaugland.crt locally
  fetch:
    dest: "temp/{{ region }}/client.jhaugland.crt"
    src: /home/adminuser/certs/client.jhaugland.crt
    flat: yes

- name: save client.jhaugland.key locally
  fetch:
    dest: "temp/{{ region }}/client.jhaugland.key"
    src: /home/adminuser/certs/client.jhaugland.key
    flat: yes
