- name: save external and internal ip addresses
  include_tasks: save-ips.yml
  when:
    - save_ips|bool

- name: create log directories
  include_tasks: create-dirs.yml

- name: save tls files locally
  include_tasks: get-crdb-tls.yml
  when:
    - get_tls|bool

- name: install cdc_sink
  include_tasks: install-cdc-sink.yml
  when:
    - install_cdc_sink|bool

- name: install java maven and go
  include_tasks: install-java-maven-go.yml
  when:
    - install_java_maven_go|bool

- name: install nodejs and typescript
  include_tasks: install-nodejs-typescript.yml
  when:
    - install_nodejs_typescript|bool

- name: add githubs
  include_tasks: add-githubs.yml
  when:
    - add_githubs|bool

- name: add password to cockroach admin role
  include_tasks: add-password.yml
  when:
    - add_password|bool

- name: start java application
  include_tasks: start-java-app.yml
  when:
    - start_java_app|bool

- name: create cdc-sink
  include_tasks: create-cdc-sink.yml
  when:
    - create_cdc_sink|bool
