- name: save external and internal ip addresses
  include_tasks: save-ips.yml
  when:
    - save_ips|bool

- name: save tls files locally
  include_tasks: get-crdb-tls.yml
  when:
    - get_tls|bool

- name: install cdc_sink
  include_tasks: install-cdc-sink.yml
  when:
    - install_cdc_sink|bool

- name: add password to cockroach admin role
  include_tasks: add-password.yml
  when:
    - add_password|bool
