- name: save external and internal ip addresses
  include_tasks: save-ips.yml
  when:
    - save_ips|bool

- name: save root crt keys
  include_tasks: get-crdb-tls.yml
  when:
    - get_crdb_tls|bool

- name: save changefeed shell script
  copy:
    content: "{{ lookup('template','create-changefeed.j2') }}"
    dest: create-changefeed.sh
    mode: '0755'
