- name: save external and internal ip addresses
  include_tasks: save-ips.yml
  when:
    - save_ips|bool

- name: generate certificates needed for crdb
  include_tasks: gen-certs.yml
  when:
    - gen_certs|bool

- name: start crdb on this node
  include_tasks: start-crdb.yml
  when:
    - start_crdb|bool

- name: save external and internal ip addresses
  include_tasks: changefeed.yml
  when:
    - changefeed|bool
