- name: Check cockroach health status
  uri:
    url: "http://localhost:8080/health"
    method: GET
    return_content: yes
    validate_certs: no
    follow_redirects: all
    headers:
        cache-control: no-cache
  register: crdb_health_result
  ignore_errors: true

- name: print the return value
  debug:
    var: crdb_health_result

- name: start crdb
  shell:
    cmd: "cockroach start --locality=region={{ region }} --certs-dir=certs --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --join={{ join_string }} --max-offset=250ms --background"
  when: crdb_health_result.status < 0
