- name: make certs dir
  become: yes
  file:
    path: /home/adminuser/certs
    state: directory
    mode: '0755'
    owner: adminuser
    group: adminuser
    recurse: yes

- name: create ca.crt
  shell:
    cmd: "echo {{ tls_cert }} >> /home/adminuser/certs/ca.crt"
    creates: /home/adminuser/certs/ca.crt

- name: create client.jhaugland.crt
  shell:
    cmd: "echo {{ tls_user_cert }} >> /home/adminuser/certs/client.{{db_admin_user}}.crt"
    creates: "/home/adminuser/certs/client.{{db_admin_user}}.crt"

- name: create client.jhaugland.key
  shell:
    cmd: "echo {{ tls_user_key }} >> /home/adminuser/certs/client.{{db_admin_user}}.key"
    creates: "/home/adminuser/certs/client.{{db_admin_user}}.key"

- name: change permissions
  become: yes
  file:
    dest: /home/adminuser/certs
    mode: '0400'
    owner: adminuser
    group: adminuser
    recurse: yes
